In [3]:
import pandas as pd
from datetime import datetime

In [4]:
df = pd.read_csv('../datasets/sravni_ru/sravni_dataset.csv')
df

,review_id,date,review_text,topic,subtopic
0,1000087,19 сентября,Вклад «Новые деньги» невозможно оформить без п...,Вклады,NaN
1,999494,18 сентября,В июне 2025 года я порекомендовал премиальную ...,Дебетовые карты,NaN
2,999142,17 сентября,Мошенниччиские аперации в интересах Ренессанс ...,Обслуживание,NaN
3,998516,15 сентября,Производил оформление открытия срочного банков...,Вклады,«Накопительный»
4,998360,15 сентября,Купил услугу Газпром Бонус «Премиум» за 2 990 ...,Дебетовые карты,NaN
...,...,...,...,...,...
4783,7470,7 апреля 2011,Ужастное обслуживание! Мало того потеряли доку...,Обслуживание,NaN
4784,7049,28 марта 2011,Могут заблокировать рассчетную или кредитную к...,Кредитные карты,NaN
4785,5221,25 января 2011,"Мало того уже прошла неделя, а ПТС так и не ве...",Автокредиты,NaN
4786,5053,16 января 2011,Газпромбанк– отличный банк с отличными сотрудн...,Ипотека,NaN
4787,4966,10 января 2011,В конце концов работают там такие же люди как ...,Кредиты наличными,NaN

In [5]:
# Словарь для замены русских месяцев (в родительном падеже)
month_map = {
    'января': '01', 'февраля': '02', 'марта': '03',
    'апреля': '04', 'мая': '05', 'июня': '06',
    'июля': '07', 'августа': '08', 'сентября': '09',
    'октября': '10', 'ноября': '11', 'декабря': '12'
}

In [6]:
# Надежная функция для конвертации даты
def convert_date(date_str):
    # Заменяем название месяца на номер
    for month_ru, month_num in month_map.items():
        if month_ru in date_str:
            date_str = date_str.replace(month_ru, month_num)
            break
            
    # Добавляем текущий год, если в строке нет года
    if len(date_str.split()) == 2:
        date_str = f"{date_str} {datetime.now().year}"
        
    # Конвертируем в datetime, используя формат с числовым месяцем
    return pd.to_datetime(date_str, format='%d %m %Y')

In [7]:
# Применяем функцию
df['date'] = df['date'].apply(convert_date)

In [8]:
df

,review_id,date,review_text,topic,subtopic
0,1000087,2025-09-19,Вклад «Новые деньги» невозможно оформить без п...,Вклады,NaN
1,999494,2025-09-18,В июне 2025 года я порекомендовал премиальную ...,Дебетовые карты,NaN
2,999142,2025-09-17,Мошенниччиские аперации в интересах Ренессанс ...,Обслуживание,NaN
3,998516,2025-09-15,Производил оформление открытия срочного банков...,Вклады,«Накопительный»
4,998360,2025-09-15,Купил услугу Газпром Бонус «Премиум» за 2 990 ...,Дебетовые карты,NaN
...,...,...,...,...,...
4783,7470,2011-04-07,Ужастное обслуживание! Мало того потеряли доку...,Обслуживание,NaN
4784,7049,2011-03-28,Могут заблокировать рассчетную или кредитную к...,Кредитные карты,NaN
4785,5221,2011-01-25,"Мало того уже прошла неделя, а ПТС так и не ве...",Автокредиты,NaN
4786,5053,2011-01-16,Газпромбанк– отличный банк с отличными сотрудн...,Ипотека,NaN
4787,4966,2011-01-10,В конце концов работают там такие же люди как ...,Кредиты наличными,NaN

In [ ]:
df.to_csv('../datasets/sravni_ru/sravni_dataset_w_corrected_dates.csv', index=False)

In [ ]:
pd.read_csv('../datasets/sravni_ru/sravni_dataset_w_corrected_dates.csv')

,review_id,date,review_text,topic,subtopic
0,1000087,2025-09-19,Вклад «Новые деньги» невозможно оформить без п...,Вклады,NaN
1,999494,2025-09-18,В июне 2025 года я порекомендовал премиальную ...,Дебетовые карты,NaN
2,999142,2025-09-17,Мошенниччиские аперации в интересах Ренессанс ...,Обслуживание,NaN
3,998516,2025-09-15,Производил оформление открытия срочного банков...,Вклады,«Накопительный»
4,998360,2025-09-15,Купил услугу Газпром Бонус «Премиум» за 2 990 ...,Дебетовые карты,NaN
...,...,...,...,...,...
4783,7470,2011-04-07,Ужастное обслуживание! Мало того потеряли доку...,Обслуживание,NaN
4784,7049,2011-03-28,Могут заблокировать рассчетную или кредитную к...,Кредитные карты,NaN
4785,5221,2011-01-25,"Мало того уже прошла неделя, а ПТС так и не ве...",Автокредиты,NaN
4786,5053,2011-01-16,Газпромбанк– отличный банк с отличными сотрудн...,Ипотека,NaN
4787,4966,2011-01-10,В конце концов работают там такие же люди как ...,Кредиты наличными,NaN